name: Trigger Private Workflow

on:
  push:
    branches:
      - main # Runs only when changes are pushed to main

jobs:
  trigger_private_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository_dispatch event
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               --data '{"event_type": "run-workflow"}' \
               https://api.github.com/repos/Ephemeral-Dust/POE2TradeUtility-Actions/dispatches
