name: Update Userscript Header for Main Branch

on:
  push:
    branches:
      - main

jobs:
  update-header:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (Main Branch)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Modify Userscript Header for Main
        run: |
          sed -i 's|@name         POE2 Trade Utility (Dev)$|@name         POE2 Trade Utility|' "POE Trade Utility.js"
          sed -i 's|@updateURL    https://raw.githubusercontent.com/Ephemeral-Dust/POE2TradeUtility/dev/POE%20Trade%20Utility.js|@updateURL    https://raw.githubusercontent.com/Ephemeral-Dust/POE2TradeUtility/main/POE%20Trade%20Utility.js|' "POE Trade Utility.js"
          sed -i 's|@downloadURL  https://raw.githubusercontent.com/Ephemeral-Dust/POE2TradeUtility/dev/POE%20Trade%20Utility.js|@downloadURL  https://raw.githubusercontent.com/Ephemeral-Dust/POE2TradeUtility/main/POE%20Trade%20Utility.js|' "POE Trade Utility.js"

          # Stage changes after modifying the header
          git add "POE Trade Utility.js"

      - name: Commit Changes (if any)
        run: |
          # Commit only if changes exist
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Commit the changes if they exist
          git diff --cached --quiet || git commit -m "Update Userscript Header for main branch" --author="github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      - name: Push changes
        run: |
          git push origin main
